spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      url: jdbc:redis://${REDIS_USER}:${REDIS_PASSWORD}@${REDIS_HOST}:${PORT}
      password: ${REDIS_PASSWORD}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


app:
  token:
    access:
      secret-key: ${JWT_SECRET_KEY_ACCESS}
      expiration: ${JWT_EXPIRATION_ACCESS}
    refresh:
      expiration: ${JWT_EXPIRATION_REFRESH}
